### PR TITLE
Ejh 20160829 backend issue10

### LINKED ISSUE #10: Barebones web backend - MVP
Blocks: #7, #8, #9
- [x] Barebones flask app on app engine
- [x] `audio/upload` POST endpoint
- [x] `annotation/submit` POST endpoint
- [x] `annotation/taxonomy` GET endpoint

### PR DESCRIPTION
**Pull request by ejhumphrey**
Will close #10, introduces a basic flask app with some minimal endpoints to start unblocking other facets of the project, plus tests and half of #3.

---
This change is [Reviewable](https://reviewable.io/reviews/omec/bedevere/15)

### CODE REVIEW

**Comment by ejhumphrey** [comment]
_now_ it's clear to be merged. I'd defer to @bmcfee or @cjacoby as resident py3 compliance experts, but anyone else is welcome to chime in.

**Comment by ejhumphrey** [comment]
Having trouble refreshing repos on coveralls, bailing for the evening ... hopefully these changes will propagate tomorrow and we can close out both #3 and #10 in this PR.

**Comment by stefan-balke** [comment]
Great!

Since this is the first PR, could you add reviewable for CR to the stack?

Thanks!

**Comment by stefan-balke** [comment]
I understand that it might be helpful to run everything with the GoogleSDK from the beginning, but couldn't we have some
```Python
if __name__ == '__main__':
    app.run(debug=True)
```

**Comment by stefan-balke** [comment]
I tested the three endpoints with the local Flask server. LGTM so far.

**Comment by ejhumphrey** [comment]
Added reviewable and the `if main` check ... still not sure what's going on with coveralls, but (a) this project still doesn't show and (b) attempting to "sync repos" spins indefinitely. maybe I'm doing it wrong, but I don't think this is a blocker just yet.

**Pull request merged**
